# This was used to generate the projections. Generated by ChatGPT as the coursework context...
# requires us to solve our work on our own, but i wanted to code a graph plot and not draw one...
# if this is still wrong then umm... sorry. but i know from terms it isn't, unless im wrong.

import matplotlib.pyplot as plt
import numpy as np

def plot_polygon(ax, points, color, label):
    """
    Plots a polygon based on given points in 2D space.

    :param ax: The matplotlib axis to plot on
    :param points: List of [x, y] coordinates representing vertices of the polygon
    :param color: Color of the polygon
    :param label: Label for the polygon
    """
    points = np.array(points)
    closed_points = np.vstack([points, points[0]])  # Close the polygon
    ax.plot(closed_points[:, 0], closed_points[:, 1], '-o', color=color, label=label)

def input_points():
    """
    Collects points from the user.

    :return: List of [x, y] coordinates
    """
    print("Input the coordinates of the points (e.g., x y). Type 'done' to finish.")
    points = []
    while True:
        inp = input("Enter point coordinates: ")
        if inp.lower() == 'done':
            break
        try:
            x, y = map(float, inp.split())
            points.append([x, y])
        except ValueError:
            print("Invalid input. Please enter coordinates in the format 'x y'.")
    return points

def main():
    print("Create your first shape.")
    points1 = input_points()

    if len(points1) < 3:
        print("You need at least 3 points to form a polygon.")
        return

    print("Now you can add another shape in red.")
    points2 = input_points()

    if len(points2) < 3:
        print("You need at least 3 points to form a polygon.")
        return

    # Plot both shapes
    fig, ax = plt.subplots(figsize=(8, 8))
    plot_polygon(ax, points1, color="blue", label="First Shape")
    plot_polygon(ax, points2, color="red", label="Second Shape")
    ax.axhline(0, color='black', linewidth=0.5, linestyle='--')
    ax.axvline(0, color='black', linewidth=0.5, linestyle='--')
    ax.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
    ax.legend()

    # Uniform scaling
    ax.set_aspect('equal', adjustable='datalim')
    ax.relim()
    ax.autoscale_view()
    plt.title("Polygon Shapes")
    plt.show()

if __name__ == "__main__":
    main()
